[package]
name = "config_types"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
deterministic_ips = { path = "../deterministic_ips" }
ic-types = { path = "../../types/types" }
url = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
serde_with = "1.6.2"
thiserror = { workspace = true }

[dev-dependencies]
once_cell = "1.8"
tempfile = { workspace = true }
