# HostOS - Base Image
#
# Build steps:
# - `docker build -t dfinity/hostos-base:<tag> -f Dockerfile.base .`
# - `docker push/pull dfinity/hostos-base:<tag>`
# - `docker build -t dfinity/hostos-base-dev:<tag> --build-arg PACKAGE_FILES="packages.common packages.dev" -f Dockerfile.base .`
# - `docker push/pull dfinity/hostos-base-dev:<tag>`
#
# NOTE:
# If you edit this file, you will need to perform the following operations
# to get your changes deployed.
#
# 1. Get your MR approved and merged into master
# 2. On the next hourly master pipeline, click the "deploy-host-os-baseimg" job
# 3. Note down the sha256 and update the sha256 reference in the neighboring
#    Dockerfiles
#

#
# First build stage:
# - Download 3rd party tools
#
FROM ubuntu:24.04 AS download

USER root:root

ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get -y update && apt-get -y upgrade && apt-get -y --no-install-recommends install \
    ca-certificates \
    curl \
    perl

# Download >=9.1 qemu and extra requirements
RUN cd /tmp/ && \
    curl -L -O http://mirrors.kernel.org/ubuntu/pool/main/n/nettle/libnettle8t64_3.10-1_amd64.deb && \
    curl -L -O http://mirrors.kernel.org/ubuntu/pool/main/n/nettle/libhogweed6t64_3.10-1_amd64.deb && \
    curl -L -O http://mirrors.kernel.org/debian/pool/main/b/brltty/libbrlapi0.8_6.7-1_amd64.deb && \
    curl -L -O http://mirrors.kernel.org/debian/pool/main/q/qemu/qemu-system-data_9.1.1+ds-2_all.deb && \
    curl -L -O http://mirrors.kernel.org/debian/pool/main/q/qemu/qemu-system-common_9.1.1+ds-2_amd64.deb && \
    curl -L -O http://mirrors.kernel.org/debian/pool/main/libj/libjpeg-turbo/libjpeg62-turbo_2.1.5-3+b1_amd64.deb && \
    curl -L -O http://mirrors.kernel.org/ubuntu/pool/main/g/gnutls28/libgnutls30t64_3.8.6-2ubuntu1_amd64.deb && \
    curl -L -O http://mirrors.kernel.org/debian/pool/main/q/qemu/qemu-system-x86_9.1.1+ds-2_amd64.deb && \
    echo "d86468a163e2792111d1550f8b5268e98bfb3aac8c5cac1ac838a17dfb0aadd6  libnettle8t64_3.10-1_amd64.deb" >> qemu.sha256 && \
    echo "69c77010697337baa9f1cb68310e8d6ba5494b89e85ef727cfed52dde46318ee  libhogweed6t64_3.10-1_amd64.deb" >> qemu.sha256 && \
    echo "c11049df22c2e201b62f3750d8c9cc99df5dead49872eca95b6a9ea3dde441df  libbrlapi0.8_6.7-1_amd64.deb" >> qemu.sha256 && \
    echo "57b6e526ac030bd4e74e4a12bd0ddf42460ac0559f33436796230f82a0bc45f2  qemu-system-data_9.1.1+ds-2_all.deb" >> qemu.sha256 && \
    echo "d665fcb4034912f89b9fe353385bc30171f442853fdddcb9cc3ccfffeed0557d  qemu-system-common_9.1.1+ds-2_amd64.deb" >> qemu.sha256 && \
    echo "c24ef7f380b7756dcfac054c3a7d1729a1b24ed659a62fe11cb4ae8793d0a31d  libjpeg62-turbo_2.1.5-3+b1_amd64.deb" >> qemu.sha256 && \
    echo "3180bdb96a896ce134b87ed2d47c484facc6cb419a6306d68e4cec7a5ff8c0ec  libgnutls30t64_3.8.6-2ubuntu1_amd64.deb" >> qemu.sha256 && \
    echo "423a54943da4fef0c7b28575f9e8180a0aa9038539027b7abf01c17ba5f56830  qemu-system-x86_9.1.1+ds-2_amd64.deb" >> qemu.sha256 && \
    shasum -c qemu.sha256

# Download >=2024-05-24 OVMF
RUN cd /tmp/ && \
    curl -L -O http://mirrors.kernel.org/debian/pool/main/e/edk2/ovmf_2024.08-4_all.deb && \
    echo "f19203f5eed55c37df3f175425ed4eae355a1380f68bf40b9ffb2bef3d7817cb  ovmf_2024.08-4_all.deb" >> ovmf.sha256 && \
    shasum -c ovmf.sha256

# Download >=10.5.0 libvirt
RUN cd /tmp/ && \
    curl -L -O http://mirrors.kernel.org/ubuntu/pool/main/libv/libvirt/libvirt-daemon-driver-qemu_10.6.0-1ubuntu3_amd64.deb && \
    curl -L -O http://mirrors.kernel.org/ubuntu/pool/main/libv/libvirt/libvirt0_10.6.0-1ubuntu3_amd64.deb && \
    curl -L -O http://mirrors.kernel.org/ubuntu/pool/main/libv/libvirt/libvirt-daemon-system-systemd_10.6.0-1ubuntu3_all.deb && \
    curl -L -O http://mirrors.kernel.org/ubuntu/pool/main/libv/libvirt/libvirt-daemon-config-nwfilter_10.6.0-1ubuntu3_all.deb && \
    curl -L -O http://mirrors.kernel.org/ubuntu/pool/main/libv/libvirt/libvirt-daemon-config-network_10.6.0-1ubuntu3_all.deb && \
    curl -L -O http://mirrors.kernel.org/ubuntu/pool/main/libv/libvirt/libvirt-daemon_10.6.0-1ubuntu3_amd64.deb && \
    curl -L -O http://mirrors.kernel.org/ubuntu/pool/main/libv/libvirt/libvirt-clients_10.6.0-1ubuntu3_amd64.deb && \
    curl -L -O http://mirrors.kernel.org/ubuntu/pool/main/libv/libvirt/libvirt-daemon-system_10.6.0-1ubuntu3_amd64.deb && \
    curl -L -O http://mirrors.kernel.org/ubuntu/pool/universe/libv/libvirt/libvirt-dev_10.6.0-1ubuntu3_amd64.deb && \
    echo "dd514ffb77dc281efd8e54bda706baafcbc3d1a1239bfc1044da799488418ac4  libvirt-daemon-driver-qemu_10.6.0-1ubuntu3_amd64.deb" >> libvirt.sha256 && \
    echo "3e53872c3da5be14d6d716c4d6da94c46ad09c10419fa9ec692026281477c716  libvirt0_10.6.0-1ubuntu3_amd64.deb" >> libvirt.sha256 && \
    echo "d2a5ae32bca1e47681cfa02fcfdb2962eca568d583fc137d72e24ac68b3b2ee2  libvirt-daemon-system-systemd_10.6.0-1ubuntu3_all.deb" >> libvirt.sha256 && \
    echo "ddbf7ceb8b3343e331cc9afc3e92e8236730dcf3ee8f558d5bc822b20561d68e  libvirt-daemon-config-nwfilter_10.6.0-1ubuntu3_all.deb" >> libvirt.sha256 && \
    echo "640746ab5bbe67d124d26585bab161835635fa402c746b135a943bad3f79a5bb  libvirt-daemon-config-network_10.6.0-1ubuntu3_all.deb" >> libvirt.sha256 && \
    echo "39c9d5d2a4c85cd09c9686346018db0081639e29adc257bc6a3d44dbe1deb9a1  libvirt-daemon_10.6.0-1ubuntu3_amd64.deb" >> libvirt.sha256 && \
    echo "1d745115767873f5c9c4137c350e0a5d6c25d137398669ffc8f9ab8c72868757  libvirt-clients_10.6.0-1ubuntu3_amd64.deb" >> libvirt.sha256 && \
    echo "34ebd13a11bf379f9c748a0102e2c66d5585354006e560e6308d892f3d889a45  libvirt-daemon-system_10.6.0-1ubuntu3_amd64.deb" >> libvirt.sha256 && \
    echo "cec3ce00ca5811e686e0a1cc24d45fb005910464b2c7040686eb1a9870b0d6e5  libvirt-dev_10.6.0-1ubuntu3_amd64.deb" >> libvirt.sha256 && \
    shasum -c libvirt.sha256

# Download >=6.11 kernel and modules
RUN cd /tmp/ && \
    curl -L -O http://mirrors.kernel.org/ubuntu/pool/main/l/linux/linux-modules-6.11.0-8-generic_6.11.0-8.8_amd64.deb && \
    curl -L -O http://mirrors.kernel.org/ubuntu/pool/main/l/linux/linux-modules-extra-6.11.0-8-generic_6.11.0-8.8_amd64.deb && \
    curl -L -O http://mirrors.kernel.org/ubuntu/pool/main/l/linux-signed/linux-image-6.11.0-8-generic_6.11.0-8.8_amd64.deb && \
    curl -L -O http://mirrors.kernel.org/ubuntu/pool/main/l/linux-meta/linux-image-generic-hwe-24.04_6.11.0-8.8_amd64.deb && \
    echo "d4cd2d97fcca81b57bec947b0e8ca004d556afce1d13f5cebe5d677c0445c6a2  linux-modules-6.11.0-8-generic_6.11.0-8.8_amd64.deb" >> kernel.sha256 && \
    echo "751be1cb9f911d84ac82d29889b956fb5c5b07c9f8ca7f74af0ff65ffbbed77c  linux-modules-extra-6.11.0-8-generic_6.11.0-8.8_amd64.deb" >> kernel.sha256 && \
    echo "241811191691c68e0874519ee71bda9de39e23510dee5e5512150db874f5b285  linux-image-6.11.0-8-generic_6.11.0-8.8_amd64.deb" >> kernel.sha256 && \
    echo "86b71d89cad0bb3e8c733d5fde9e96f293b8ba3d98ea42ddd47d5b53501e5b84  linux-image-generic-hwe-24.04_6.11.0-8.8_amd64.deb" >> kernel.sha256 && \
    shasum -c kernel.sha256

# Download and verify node_exporter
RUN cd /tmp/ && \
    curl -L -O https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz && \
    echo "fbadb376afa7c883f87f70795700a8a200f7fd45412532cc1938a24d41078011  node_exporter-1.8.1.linux-amd64.tar.gz" > node_exporter.sha256 && \
    shasum -c node_exporter.sha256


#
# Second build stage:
# - Download and cache minimal Ubuntu Server 20.04 LTS Docker image.
# - Install and cache upstream packages from built-in Ubuntu repositories.
# - Install compiled packages from the second stage.
#
FROM ubuntu:24.04

USER root:root

ARG CPU_SUPPORT
ENV SOURCE_DATE_EPOCH=0
ENV TZ=UTC
ENV DEBIAN_FRONTEND=noninteractive


# For the prod image, just use packages.common to define the packages installed
# on target.
# For the dev image, use both "packages.common" and "packages.dev" -- this can
# be set via docker build args (see above).
ARG PACKAGE_FILES=packages.common
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
COPY packages.* /tmp/
RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get -y --no-install-recommends install $(for P in ${PACKAGE_FILES}; do cat /tmp/$P | sed -e "s/#.*//" ; done) && \
    rm /tmp/packages.*

# Install >=9.1 qemu and extra requirements
COPY --from=download /tmp/libnettle8t64_3.10-1_amd64.deb /tmp/libnettle8t64_3.10-1_amd64.deb
COPY --from=download /tmp/libhogweed6t64_3.10-1_amd64.deb /tmp/libhogweed6t64_3.10-1_amd64.deb
COPY --from=download /tmp/libbrlapi0.8_6.7-1_amd64.deb /tmp/libbrlapi0.8_6.7-1_amd64.deb
COPY --from=download /tmp/qemu-system-data_9.1.1+ds-2_all.deb /tmp/qemu-system-data_9.1.1+ds-2_all.deb
COPY --from=download /tmp/qemu-system-common_9.1.1+ds-2_amd64.deb /tmp/qemu-system-common_9.1.1+ds-2_amd64.deb
COPY --from=download /tmp/libjpeg62-turbo_2.1.5-3+b1_amd64.deb /tmp/libjpeg62-turbo_2.1.5-3+b1_amd64.deb
COPY --from=download /tmp/libgnutls30t64_3.8.6-2ubuntu1_amd64.deb /tmp/libgnutls30t64_3.8.6-2ubuntu1_amd64.deb
COPY --from=download /tmp/qemu-system-x86_9.1.1+ds-2_amd64.deb /tmp/qemu-system-x86_9.1.1+ds-2_amd64.deb

RUN apt-get install -y --no-install-recommends \
    /tmp/libnettle8t64_3.10-1_amd64.deb \
    /tmp/libhogweed6t64_3.10-1_amd64.deb \
    /tmp/libbrlapi0.8_6.7-1_amd64.deb \
    /tmp/qemu-system-data_9.1.1+ds-2_all.deb \
    /tmp/qemu-system-common_9.1.1+ds-2_amd64.deb \
    /tmp/libjpeg62-turbo_2.1.5-3+b1_amd64.deb \
    /tmp/libgnutls30t64_3.8.6-2ubuntu1_amd64.deb \
    /tmp/qemu-system-x86_9.1.1+ds-2_amd64.deb && \
    rm /tmp/libnettle8t64_3.10-1_amd64.deb && \
    rm /tmp/libhogweed6t64_3.10-1_amd64.deb && \
    rm /tmp/libbrlapi0.8_6.7-1_amd64.deb && \
    rm /tmp/qemu-system-data_9.1.1+ds-2_all.deb && \
    rm /tmp/qemu-system-common_9.1.1+ds-2_amd64.deb && \
    rm /tmp/libjpeg62-turbo_2.1.5-3+b1_amd64.deb && \
    rm /tmp/libgnutls30t64_3.8.6-2ubuntu1_amd64.deb && \
    rm /tmp/qemu-system-x86_9.1.1+ds-2_amd64.deb

# Install >=2024-05-24 OVMF
COPY --from=download /tmp/ovmf_2024.08-4_all.deb /tmp/ovmf_2024.08-4_all.deb

RUN apt-get install -y --no-install-recommends \
    /tmp/ovmf_2024.08-4_all.deb && \
    rm /tmp/ovmf_2024.08-4_all.deb

# Install >=10.5.0 libvirt
COPY --from=download /tmp/libvirt-daemon-driver-qemu_10.6.0-1ubuntu3_amd64.deb /tmp/libvirt-daemon-driver-qemu_10.6.0-1ubuntu3_amd64.deb
COPY --from=download /tmp/libvirt0_10.6.0-1ubuntu3_amd64.deb /tmp/libvirt0_10.6.0-1ubuntu3_amd64.deb
COPY --from=download /tmp/libvirt-daemon-system-systemd_10.6.0-1ubuntu3_all.deb /tmp/libvirt-daemon-system-systemd_10.6.0-1ubuntu3_all.deb
COPY --from=download /tmp/libvirt-daemon-config-nwfilter_10.6.0-1ubuntu3_all.deb /tmp/libvirt-daemon-config-nwfilter_10.6.0-1ubuntu3_all.deb
COPY --from=download /tmp/libvirt-daemon-config-network_10.6.0-1ubuntu3_all.deb /tmp/libvirt-daemon-config-network_10.6.0-1ubuntu3_all.deb
COPY --from=download /tmp/libvirt-daemon_10.6.0-1ubuntu3_amd64.deb /tmp/libvirt-daemon_10.6.0-1ubuntu3_amd64.deb
COPY --from=download /tmp/libvirt-clients_10.6.0-1ubuntu3_amd64.deb /tmp/libvirt-clients_10.6.0-1ubuntu3_amd64.deb
COPY --from=download /tmp/libvirt-daemon-system_10.6.0-1ubuntu3_amd64.deb /tmp/libvirt-daemon-system_10.6.0-1ubuntu3_amd64.deb
COPY --from=download /tmp/libvirt-daemon-system_10.6.0-1ubuntu3_amd64.deb /tmp/libvirt-daemon-system_10.6.0-1ubuntu3_amd64.deb
COPY --from=download /tmp/libvirt-dev_10.6.0-1ubuntu3_amd64.deb /tmp/libvirt-dev_10.6.0-1ubuntu3_amd64.deb

RUN apt-get install -y --no-install-recommends \
    /tmp/libvirt-daemon-driver-qemu_10.6.0-1ubuntu3_amd64.deb \
    /tmp/libvirt0_10.6.0-1ubuntu3_amd64.deb \
    /tmp/libvirt-daemon-system-systemd_10.6.0-1ubuntu3_all.deb \
    /tmp/libvirt-daemon-config-nwfilter_10.6.0-1ubuntu3_all.deb \
    /tmp/libvirt-daemon-config-network_10.6.0-1ubuntu3_all.deb \
    /tmp/libvirt-daemon_10.6.0-1ubuntu3_amd64.deb \
    /tmp/libvirt-clients_10.6.0-1ubuntu3_amd64.deb \
    /tmp/libvirt-daemon-system_10.6.0-1ubuntu3_amd64.deb && \
    /tmp/libvirt-dev_10.6.0-1ubuntu3_amd64.deb && \
    rm /tmp/libvirt-daemon-driver-qemu_10.6.0-1ubuntu3_amd64.deb && \
    rm /tmp/libvirt0_10.6.0-1ubuntu3_amd64.deb && \
    rm /tmp/libvirt-daemon-system-systemd_10.6.0-1ubuntu3_all.deb && \
    rm /tmp/libvirt-daemon-config-nwfilter_10.6.0-1ubuntu3_all.deb && \
    rm /tmp/libvirt-daemon-config-network_10.6.0-1ubuntu3_all.deb && \
    rm /tmp/libvirt-daemon_10.6.0-1ubuntu3_amd64.deb && \
    rm /tmp/libvirt-clients_10.6.0-1ubuntu3_amd64.deb && \
    rm /tmp/libvirt-daemon-system_10.6.0-1ubuntu3_amd64.deb && \
    rm /tmp/libvirt-dev_10.6.0-1ubuntu3_amd64.deb

# Install >=6.11 kernel
COPY --from=download /tmp/linux-modules-6.11.0-8-generic_6.11.0-8.8_amd64.deb /tmp/linux-modules-6.11.0-8-generic_6.11.0-8.8_amd64.deb
COPY --from=download /tmp/linux-modules-extra-6.11.0-8-generic_6.11.0-8.8_amd64.deb /tmp/linux-modules-extra-6.11.0-8-generic_6.11.0-8.8_amd64.deb
COPY --from=download /tmp/linux-image-6.11.0-8-generic_6.11.0-8.8_amd64.deb /tmp/linux-image-6.11.0-8-generic_6.11.0-8.8_amd64.deb
COPY --from=download /tmp/linux-image-generic-hwe-24.04_6.11.0-8.8_amd64.deb /tmp/linux-image-generic-hwe-24.04_6.11.0-8.8_amd64.deb

RUN apt-get install -y --no-install-recommends \
    /tmp/linux-modules-6.11.0-8-generic_6.11.0-8.8_amd64.deb \
    /tmp/linux-modules-extra-6.11.0-8-generic_6.11.0-8.8_amd64.deb \
    /tmp/linux-image-6.11.0-8-generic_6.11.0-8.8_amd64.deb \
    /tmp/linux-image-generic-hwe-24.04_6.11.0-8.8_amd64.deb && \
    rm /tmp/linux-modules-6.11.0-8-generic_6.11.0-8.8_amd64.deb && \
    rm /tmp/linux-modules-extra-6.11.0-8-generic_6.11.0-8.8_amd64.deb && \
    rm /tmp/linux-image-6.11.0-8-generic_6.11.0-8.8_amd64.deb && \
    rm /tmp/linux-image-generic-hwe-24.04_6.11.0-8.8_amd64.deb

# Install node_exporter
COPY --from=download /tmp/node_exporter-1.8.1.linux-amd64.tar.gz /tmp/node_exporter-1.8.1.linux-amd64.tar.gz
RUN cd /tmp/ && \
    mkdir -p /etc/node_exporter && \
    tar --strip-components=1 -C /usr/local/bin/ -zvxf node_exporter-1.8.1.linux-amd64.tar.gz node_exporter-1.8.1.linux-amd64/node_exporter && \
    rm /tmp/node_exporter-1.8.1.linux-amd64.tar.gz
